In [1]:
import spacy

from spacy.lang.en.stop_words import STOP_WORDS

STOP_WORDS

{"'d",
 "'ll",
 "'m",
 "'re",
 "'s",
 "'ve",
 'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'both',
 'bottom',
 'but',
 'by',
 'ca',
 'call',
 'can',
 'cannot',
 'could',
 'did',
 'do',
 'does',
 'doing',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fifty',
 'first',
 'five',
 'for',
 'former',
 'formerly',
 'forty',
 'four',
 'from',
 'front',
 'full',
 'further',
 'get',
 'give',
 'go',
 'had',
 'has',
 'have',
 'he',
 'hence',
 'her',
 'here',
 'hereafter',
 'hereby',
 'herein',
 'hereupon',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'however',
 'hundred',
 'i',
 'if',
 'in',
 'indeed',
 'into',
 'is',
 'it',
 'its',
 'itself',
 'just',
 'keep',
 'last',
 'latter',
 'latterly',
 'least',
 'less',
 'made',
 'make',
 'many',
 'may',
 'me',
 'meanwhile',
 'might',
 'mine',
 'more',
 'moreover',
 'most',
 'mostly',
 'move',
 'much',
 'must',
 'my',
 'myself',
 "n't",
 'name',
 'namely',
 'neither',
 'never',
 'nevertheless',
 'next',
 'nine',
 'no',
 'nobody',
 'none',
 'noone',
 'nor',
 'not',
 'nothing',
 'now',
 'nowhere',
 'n‘t',
 'n’t',
 'of',
 'off',
 'often',
 'on',
 'once',
 'one',
 'only',
 'onto',
 'or',
 'other',
 'others',
 'otherwise',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'part',
 'per',
 'perhaps',
 'please',
 'put',
 'quite',
 'rather',
 're',
 'really',
 'regarding',
 'same',
 'say',
 'see',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'serious',
 'several',
 'she',
 'should',
 'show',
 'side',
 'since',
 'six',
 'sixty',
 'so',
 'some',
 'somehow',
 'someone',
 'something',
 'sometime',
 'sometimes',
 'somewhere',
 'still',
 'such',
 'take',
 'ten',
 'than',
 'that',
 'the',
 'their',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 'thereafter',
 'thereby',
 'therefore',
 'therein',
 'thereupon',
 'these',
 'they',
 'third',
 'this',
 'those',
 'though',
 'three',
 'through',
 'throughout',
 'thru',
 'thus',
 'to',
 'together',
 'too',
 'top',
 'toward',
 'towards',
 'twelve',
 'twenty',
 'two',
 'under',
 'unless',
 'until',
 'up',
 'upon',
 'us',
 'used',
 'using',
 'various',
 'very',
 'via',
 'was',
 'we',
 'well',
 'were',
 'what',
 'whatever',
 'when',
 'whence',
 'whenever',
 'where',
 'whereafter',
 'whereas',
 'whereby',
 'wherein',
 'whereupon',
 'wherever',
 'whether',
 'which',
 'while',
 'whither',
 'who',
 'whoever',
 'whole',
 'whom',
 'whose',
 'why',
 'will',
 'with',
 'within',
 'without',
 'would',
 'yet',
 'you',
 'your',
 'yours',
 'yourself',
 'yourselves',
 '‘d',
 '‘ll',
 '‘m',
 '‘re',
 '‘s',
 '‘ve',
 '’d',
 '’ll',
 '’m',
 '’re',
 '’s',
 '’ve'}

In [4]:
len(STOP_WORDS)

326

In [5]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("We just opened our wings, the flying part is coming soon")

for token in doc:
    if token.is_stop:
        print(token)

We
just
our
the
part
is

In [16]:
# To get a List

def preprocess(text):
    doc = nlp(text)

    no_stop_words = [token.text for token in doc if not token.is_stop and not token.is_punct]

    return no_stop_words

In [7]:
preprocess("We just opened our wings, the flying part is coming soon")

['opened', 'wings', 'flying', 'coming', 'soon']

In [9]:
import pandas as pd

df = pd.read_json(r"F:\Codes\NLP\combined.json",lines=True)

df.shape

(13087, 6)

In [10]:
df.head(4)

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]

In [11]:
df.info

<bound method DataFrame.info of             id                                              title  \
0         None       Convicted Bomb Plotter Sentenced to 30 Years
1      12-919   $1 Million in Restitution Payments Announced t...
2      11-1002  $1 Million Settlement Reached for Natural Reso...
3       10-015  10 Las Vegas Men Indicted \r\nfor Falsifying V...
4       18-898  $100 Million Settlement Will Speed Cleanup Wor...
...        ...                                                ...
13082   16-735  Yuengling to Upgrade Environmental Measures to...
13083   10-473  Zarein Ahmedzay Pleads Guilty to Terror Violat...
13084   17-045  Zimmer Biomet Holdings Inc. Agrees to Pay $17....
13085   17-252  ZTE Corporation Agrees to Plead Guilty and Pay...
13086   17-304  ZTE Corporation Pleads Guilty for  Violating U...

                                                contents  \
0      PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...
1        WASHINGTON – North Carolina’s Waccamaw River...
2            BOSTON– A $1-million settlement has been...
3        WASHINGTON—A federal grand jury in Las Vegas...
4      The U.S. Department of Justice, the U.S. Envir...
...                                                  ...
13082  The Department of Justice and the U.S. Environ...
13083    The Justice Department announced that Zarein...
13084  Subsidiary Agrees to Plead Guilty to Violating...
13085  ZTE Corporation has agreed to enter a guilty p...
13086  ZTE Corporation pleaded guilty today to conspi...

                            date  \
0      2014-10-01T00:00:00-04:00
1      2012-07-25T00:00:00-04:00
2      2011-08-03T00:00:00-04:00
3      2010-01-08T00:00:00-05:00
4      2018-07-09T00:00:00-04:00
...                          ...
13082  2016-06-23T00:00:00-04:00
13083  2010-04-23T00:00:00-04:00
13084  2017-01-12T00:00:00-05:00
13085  2017-03-07T00:00:00-05:00
13086  2017-03-22T00:00:00-04:00

                                                  topics  \
0                                                     []
1                                                     []
2                                                     []
3                                                     []
4                                          [Environment]
...                                                  ...
13082                                      [Environment]
13083                                                 []
13084                               [Foreign Corruption]
13085  [Asset Forfeiture, Counterintelligence and Exp...
13086           [Counterintelligence and Export Control]

                                              components
0                     [National Security Division (NSD)]
1           [Environment and Natural Resources Division]
2           [Environment and Natural Resources Division]
3           [Environment and Natural Resources Division]
4           [Environment and Natural Resources Division]
...                                                  ...
13082       [Environment and Natural Resources Division]
13083                   [Office of the Attorney General]
13084  [Criminal Division, Criminal - Criminal Fraud ...
13085  [National Security Division (NSD), USAO - Texa...
13086  [National Security Division (NSD), USAO - Texa...

[13087 rows x 6 columns]>

In [12]:
df.describe

<bound method NDFrame.describe of             id                                              title  \
0         None       Convicted Bomb Plotter Sentenced to 30 Years
1      12-919   $1 Million in Restitution Payments Announced t...
2      11-1002  $1 Million Settlement Reached for Natural Reso...
3       10-015  10 Las Vegas Men Indicted \r\nfor Falsifying V...
4       18-898  $100 Million Settlement Will Speed Cleanup Wor...
...        ...                                                ...
13082   16-735  Yuengling to Upgrade Environmental Measures to...
13083   10-473  Zarein Ahmedzay Pleads Guilty to Terror Violat...
13084   17-045  Zimmer Biomet Holdings Inc. Agrees to Pay $17....
13085   17-252  ZTE Corporation Agrees to Plead Guilty and Pay...
13086   17-304  ZTE Corporation Pleads Guilty for  Violating U...

                                                contents  \
0      PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...
1        WASHINGTON – North Carolina’s Waccamaw River...
2            BOSTON– A $1-million settlement has been...
3        WASHINGTON—A federal grand jury in Las Vegas...
4      The U.S. Department of Justice, the U.S. Envir...
...                                                  ...
13082  The Department of Justice and the U.S. Environ...
13083    The Justice Department announced that Zarein...
13084  Subsidiary Agrees to Plead Guilty to Violating...
13085  ZTE Corporation has agreed to enter a guilty p...
13086  ZTE Corporation pleaded guilty today to conspi...

                            date  \
0      2014-10-01T00:00:00-04:00
1      2012-07-25T00:00:00-04:00
2      2011-08-03T00:00:00-04:00
3      2010-01-08T00:00:00-05:00
4      2018-07-09T00:00:00-04:00
...                          ...
13082  2016-06-23T00:00:00-04:00
13083  2010-04-23T00:00:00-04:00
13084  2017-01-12T00:00:00-05:00
13085  2017-03-07T00:00:00-05:00
13086  2017-03-22T00:00:00-04:00

                                                  topics  \
0                                                     []
1                                                     []
2                                                     []
3                                                     []
4                                          [Environment]
...                                                  ...
13082                                      [Environment]
13083                                                 []
13084                               [Foreign Corruption]
13085  [Asset Forfeiture, Counterintelligence and Exp...
13086           [Counterintelligence and Export Control]

                                              components
0                     [National Security Division (NSD)]
1           [Environment and Natural Resources Division]
2           [Environment and Natural Resources Division]
3           [Environment and Natural Resources Division]
4           [Environment and Natural Resources Division]
...                                                  ...
13082       [Environment and Natural Resources Division]
13083                   [Office of the Attorney General]
13084  [Criminal Division, Criminal - Criminal Fraud ...
13085  [National Security Division (NSD), USAO - Texa...
13086  [National Security Division (NSD), USAO - Texa...

[13087 rows x 6 columns]>

In [13]:
df = df[df["topics"].str.len() != 0]
df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [17]:
# To get a string

def preprocess(text):
    doc = nlp(text)
    
    no_stop_words = [token.text for token in doc if not token.is_stop]
    return " ".join(no_stop_words)

In [18]:
preprocess("Musk wants time to prepare for a trial over his")

'Musk wants time prepare trial'

In [19]:
len(df["contents"].iloc[4])

5504

In [ ]:
df["contents_new"] = df["contents"].apply(preprocess)

df

In [23]:
len(df.contents[4])

6286

In [25]:
len(df.contents_new[4])

4810

In [26]:
df.contents[4][:300]

'The U.S. Department of Justice, the U.S. Environmental Protection Agency (EPA), and the Rhode Island Department of Environmental Management (RIDEM) announced today that two subsidiaries of Stanley Black & Decker Inc.—Emhart Industries Inc. and Black & Decker Inc.—have agreed to clean up dioxin conta'

In [27]:
df.contents_new[4][:300]

'U.S. Department Justice , U.S. Environmental Protection Agency ( EPA ) , Rhode Island Department Environmental Management ( RIDEM ) announced today subsidiaries Stanley Black & Decker Inc.—Emhart Industries Inc. Black & Decker Inc.—have agreed clean dioxin contaminated sediment soil Centredale Manor'